### ISSUE TITLE
calendar not updating

### ISSUE THREAD

**Issue by benderstwin** [eouia/MMM-CalendarExt2#1]
This module is awesome!  I have 2 issues.

#1:  Calendar wont update.  The only way I can get it to update is to restart magicmirror.  It's refreshing per the set interval, but it doesnt pull in any new events.

#2: In the view "current", it's only listing 1 event.  I have maxEvents set to 5.

config

```{
			module: 'MMM-CalendarExt2',
			config: {
			  updateInterval: 1000*10,
			  defaultSet: {
				view: {
				  hideOverflow:true,
				}
			  },
			  calendars : [
				{
				  name: "US holiday",
				  icon: "noto-beach-with-umbrella",
				  className: "holiday",
				  url: "http://www.calendarlabs.com/templates/ical/US-Holidays.ics",
				},
		  
				{
				  name : "Household",
				  icon: "noto-soccer-ball",
				  url: "privateics",
				},
		  
				
			  ],
			  views: [
				views: [
				{
				  name: "TODAY",
				  mode: "current",
				  slotTitle: "TODAY",
				  calendars: ["Household", "US holiday"],
				  position: "top_right",
				  maxItems: 5,
				  useEventTimeRelative: "true",
				},
				{
				  name: "VIEW1",
				  mode: "daily",
				  title: "upcoming",
				  calendars: ["Household", "US holiday"],
				  position: "bottom_bar",
				  fromNow: +1,
				  type: "row",
				  slotCount: 3,
				},
				{
				  name: "VIEW2",
				  mode: "month",
				  title: "All ",
				  calendars: [],
				  position: "fullscreen_below",
				},
		  
			  ],
			  scenes: [
				{
				  name: "DEFAULT",
				  views:["VIEW1", "TODAY"],
				},
				{
				  name: "ONLY_VIEW2",
				  views:["VIEW2"]
				},
				{
				  name: "ONLY_VIEW1",
				  views:["VIEW1"]
				}
			  ],
			},
		  },
```

Thank you for this module!

**Comment by eouia** [comment]
1 each calendar.scanInterval, new updated events will be fetched.
2. Current will show events which is going on NOW, so if your current event is just one, then only one event will show.

**Comment by eouia** [comment]
Have you still this issue? I'll close this if there is no more question.
I wish you good luck. Have a nice day.

**Comment by thebmfinn** [comment]
I am having the same issue, if I add events to my google calendar the events only show up on after power cycling. I have my scanInterval set to 2 minutes (1000*60*2)... Anything I can try?
