### ISSUE TITLE
Filtering on calendar level doesn't work

### ISSUE THREAD

**Issue by klaernie** [eouia/MMM-CalendarExt2#11]
Hi there,

I am delighted by this modules, and upon migration from MMM-CalendarExt wanted to use the new functionality to filter not on the View level, but on the calendar level instead. But taking a look at the node_helper doesn't show any place that actually calls the filter function specified in the calendar.

But if I in turn move my filter over into the view I can filter there just fine, but that means that pretty large event list needs to be transferred over and over again, just to be reduced in the front end JS code.

Could it be, that this implementation is just missing?

Thanks and best regards,

**Comment by eouia** [comment]
Long days passed, so I cannot remember sure. I'll review my code and tell you precisely.

**Comment by eouia** [comment]
I'd missed that implementation on release time. There was some problem on that feature, so I postponed it later, but I've been forgetting it.
It is difficult to filter it on fetching time. But I think I can add filtering after fetching before transferring it to the main module.

**Comment by eouia** [comment]
I've updated. plz test it.

**Comment by klaernie** [comment]
Works perfectly, thanks a lot!
