### ISSUE TITLE
Example Configs

### ISSUE THREAD

**Issue by klaernie** [eouia/MMM-CalendarExt2#14]
Would you be open to have a library of example configs somewhere around the repo?

I now reached the point where my config looks like it should, and how my girlfriend approves. And considering the relatively young age for MMM-CalendarExt2 I think it would be nice to provide some fully fledged examples that showcase what can be done, and what one needs to do in order to achieve this.

For example I went for a rather plain looking style, more adapted to the default look of MagicMirror, and I'm also a heavy user of filtering on the calendar level. Finally as we have 6 calendars for three people also some differentiation between the calendars was needed.
![image](https://user-images.githubusercontent.com/5636383/55021330-d7a66200-4ff8-11e9-9071-84ad8f38e37b.png)

**Comment by eouia** [comment]
Good idea. How about using wiki?

**Comment by eouia** [comment]
Or you can make tutorial.md as pr

**Comment by leonrosen** [comment]
Just what I've been dreaming about!  Please share examples as I find I learn from them the most.

**Comment by klaernie** [comment]
@leonrosen take a look and tell me how it reads: #15
