### ISSUE TITLE
`maxDays` in upcoming view doesn't work

### ISSUE THREAD

**Issue by klaernie** [eouia/MMM-CalendarExt2#19]
From pretty much the start of my config I had set my [upcoming view's `maxDays`](https://github.com/eouia/MMM-CalendarExt2/blob/master/doc/Configuration/Views/current%2C-upcoming.md) to `1`, in order to only show today's events.

But checking against the code I don't see where this is done, as [`ViewUpcoming's filterEvents()`](https://github.com/eouia/MMM-CalendarExt2/blob/7670c27ed27949bf52a2fab7cd709823f0eb3867/CALEXT2_View.js#L560) only filters out events that begin in the past.

**Comment by eouia** [comment]
You are right.
I might have forgotten add that routine in `filterEvents()` of `ViewUpcoming` class. Sorry.
I'll add it on next updates. I think I did some mistake about it on first commit.

**Comment by eouia** [comment]
updated. Sorry again.

**Comment by klaernie** [comment]
Thanks a lot. What does happen, when `maxDays` is `null`? Would this mean `24h` is default, or does `inBetween()` clever enough to choose infinitily in the future instead?

**Comment by eouia** [comment]
By default configuration, `maxDays` cannot be null. (I didn't want to overwrite null to missed config, so `initConfig()` will keep default values for un-overwritten fields - I hope. nowadays I couldn't believe my code any more. :D )
but, if you set it as null by force. Hmmm. I didn't test it. `0` is available, but `null`.. hmmm.. Maybe it's better to add routine for check.

**Comment by klaernie** [comment]
I'm probably just overly cautious. But I definitely missed that there is an actual default value, that the user config just overwrites.

As nowhere else such checks exists I think it isn't warranted here either.
-- 
Andre Klärner

Telefon: 0351/20920918
Mobil:   0172/9838653

Anschrift:
Wallstraße 21
01067 Dresden
