### ISSUE TITLE
Week numbers & Weekends

### ISSUE THREAD

**Issue by qwertyjon** [eouia/MMM-CalendarExt2#22]
I've moved over to CalendarExt2 and I'm having some problems with the week view.
1. How do I remove the week numbers?, I've tried `weeksFormat: ""` and `weeksFormat: [ ]`
2. How do I start the week on a Monday, not a Sunday?

Sorry, I'm very new to this.

**Comment by eouia** [comment]
Sorry to late reply.
1. You can hide weeknumber by modify css. Add this to `css/custom.css`;
```css
.CX2 .weeksmark {
  display:none;
```
2. It depends on which locale are you using. If you are using `en-US`, Week will start from Sunday. In case of `en-GB`, starts from Monday.

**Comment by ingo916** [comment]
Where do i change the local?

**Comment by ingo916** [comment]
where do i change the local in MMM-CalendarEXT2?
