### ISSUE TITLE
 custom css not working

### ISSUE THREAD

**Issue by Aikagi000** [eouia/MMM-CalendarExt2#23]
I'm trying to change the look of the calendar. I have a css folder inside the MMM-CalendarExt2 folder... and my custom.css is there. 

in that file all I have is:

.CX2 .slot > .slotContent {
  position: relative;
  width: 100%;
  background-image: linear-gradient(rgba(0,0,0,.2), rgba(0,0,0,0));
}

Won't take. Am I missing something?

also, for some reason the module has a huge header on the screen "MMM-Calendar2 / module_5_MMM-CalendarExt2" how do i get rid of that?

**Comment by Aikagi000** [comment]
Ok I figured it out. Any changes to the css goes in the custom.css that is in the **css folder at the root of the MagicMirror Directory.**

Recommend clearly stating that in the instructions for those coming from the old calendarExt that had the css changes in it's own folder. I'm a noob sorry lol.

**Comment by eouia** [comment]
sorry for unconvenience. MMM-CalendarExt was developed when I was not experienced to MM, so I had made some mistakes to name `custom.css` in module folder.
