### ISSUE TITLE
How to config similar to this screenshot

### ISSUE THREAD

**Issue by mlcampbe** [eouia/MMM-CalendarExt2#27]
I'm trying to configure a clean/simple calendar showing mine and my wife's events from our google calendar. I've had no real luck in configuring this module. Can you give me some pointers to a way to configure the calendar so it looks similar to the below screenshot? Ignore the date/time/weather but I am just looking for a calendar module that displays in the below format.

![Imgur](https://i.imgur.com/s7mgolt.png)

**Comment by mlcampbe** [comment]
I played with it some more and got something that will work for me. Closing this question.

**Comment by DanielNagy** [comment]
Hi @mlcampbe,

I'd love for you to share your configs as i absolutely love this clean layout

Thanks!

**Comment by mlcampbe** [comment]
Take a look at https://forum.magicmirror.builders/topic/11001/config-for-a-simple-clean-montly-calendar/10 which is what I came up with. Not exactly like the screenshot here from which was from Dakboard.
