### ISSUE TITLE
Can we display the month name in 'month' mode?

### ISSUE THREAD

**Issue by mlcampbe** [eouia/MMM-CalendarExt2#29]
As the title says. I have a single scene with 1 view that displays several calendars. This is working fine but wanted to see if there is a way to display the current month/year as a header. I see the title parameter for a view but that seems to be static text. Any way to make this dynamic?

**Comment by eouia** [comment]
no, sorry. i'll consider it on next update but not guaranted.

**Comment by eouia** [comment]
I've added that feature.
