### ISSUE TITLE
Nothing showing

### ISSUE THREAD

**Issue by mishu28nmv** [eouia/MMM-CalendarExt2#32]
Hy to all and thanks for your work.
Can someone help, because I don't see the calendar module at all.
Here is my config:
```{
			module: 'MMM-CalendarExt2',
			config: {
				calendars : [
				{
	name: "Mihai",
	icon: "noto-v1:beaming-face-with-smiling-eyes",
	url: 'https://calendar.google.com/calendar/ical/blabla/private-blablabla/basic.ics',
				},
				{
	name: "Romania",
	icon: "twemoji:flag-for-romania",
	url: 'https://calendar.google.com/calendar/embed?src=ro.romanian%23holiday%40group.v.calendar.google.com&ctz=Europe%2FBerlin',
				},
				{
	name: "Kita",
	icon: "noto:family-man-woman-girl",
	url: 'https://calendar.google.com/calendar/ical/blblbla.calendar.google.com/private-blablabla/basic.ics',
				},
					],
				views: [
				{
    name: "Mishu",
    mode: "upcoming",
    position: "bottom_bar",
    calendars: ["Mihai", "Kita"]
				},
				{
	name: "Rom",
    mode: "upcoming",
    position: "bottom_bar",
    calendars: ["Romania"],
				},
					],
				scenes: [
				{
        name: "Default",
	views: ["Mishu", "Rom"]
				},
					]
				}
},```

**Comment by eouia** [comment]
first, `upcoming` view looks not so pretty on `bar` position. Or you should modify CSS as your wish.

I think you might have plenty of events on the calendars. set `maxItems` of `view` to bigger values. For the performance issue, it is limited with 100 by default. Enlarge it to fit your calendars.

**Comment by mishu28nmv** [comment]
Thank you and I'm sorry for writing the code like that. I copyied through VNC Viewer. How can I post an image?

**Comment by eouia** [comment]
just drag and drop under section of  the textbox

**Comment by mishu28nmv** [comment]
Still nothing.
![2019-10-03-232748_800x480_scrot](https://user-images.githubusercontent.com/42743265/66165894-09e2ed00-e636-11e9-83d3-6916fb5b08e2.png)

```{
		module: "MMM-CalendarExt2",
			config: {
			scenes: [
				{
		name: "DEFAULT",
		views: ["Mishu", "Rom"]
				},
				],
			views: [
				{
		name: "Mishu",
		mode: "upcoming",
		position: "top_left",
		maxItems: 5,
		maxDays: 1,
		hideOverflow: false,
		filterPassedEvent: true,
		calendars: ["Mihai", "Kita"],
				},
				{
		name: "Rom",
		title: "Sărbători România",
		mode: "daily",
		maxItems: 100,
		scanInterval: 1000*60*30,
		type: "row",
		position: "bottom_bar",
		slotCount: 5,
		hideOverflow: false,
		filterPassedEvent: true,
		calendars: ["Romania"],
				},
			],
			calendars: [
				{
	name: "Mihai",
	icon: "noto-v1:beaming-face-with-smiling-eyes",
	url: 'https://calendar.google.com/calendar/yyy/basic.ics',
				},
				{
	name: "Romania",
	icon: "twemoji:flag-for-romania",
	url: 'https://calendar.google.com/calendar/embed?src=ro.romanian%23holiday%40group.v.calendar.google.com&ctz=Europe%2FBerlin',
				},
				{
	name: "Kita",
	icon: "noto:family-man-woman-girl",
	url: 'https://calendar.google.com/calendar/ical/xxx/basic.ics',
				},
				   ],
				},
		},

**Comment by MerlijnAlmer** [comment]
@mishu28nmv you are sure you dont have another module above it in your config file that doesn't have a location.
for some reason when i was testing my calendar and i would just have it like this. it also wouldn't show.
i think it is bacause the module above in this case clock doesn't have a position.
so i put the MMM-CalendarExt2 module above it and it worked.
`	modules: [
                        {
                        module: "clock",
			position: "",
			config: {
			    timeFormat: "24",
			    displaySeconds: "true",
			    clockBold: "true",
			    displayType: "both",
			    anologFace: "face-006",
			    timeZone: "Europe/Amsterdam",
			}
		},
		{
  		module: "MMM-CalendarExt2",
		  config: {....},`

**Comment by Lotusvball** [comment]
I too am getting nothing and everything has a position.  

{
			module: 'MMM-CalendarExt2',
			config: {
				scenes:[
					{
						name: "DEFAULT",
						views: ["upcoming"],
					},
				],
				views:[
					{
						name: "upcoming",
						mode: "upcoming",
						position: "bottom_center",
						maxItems: 5,
						maxDays: 1,
						locale: "en",
						hideOverflow: false,
						filterPassedEvent: true,
						calendars: ["Steve"],
					},
				],
				calendars: [
					{
						name: "Steve",
						url: "https://calendar.google.com/calendar/ical/sabard%40gmail.com/private-817ab860d8166392a841503f0cd9d6ed/basic.ics",
					},
				],
			},
		},

**Comment by eouia** [comment]
You've set `maxItems` too small. `maxItems:5` means letting your `upcoming view` load at most 5 events from calendars. but usually, your calendar would have more than 5, but the view will load only 5. And unless you `filter` or `sort`, the events loaded might not match your `filterPassedEvent:true` and `maxDays:1`. 
Give enough value to `maxItems`, by example, 100 or more. 
![image](https://user-images.githubusercontent.com/1720610/66736064-8365b100-ee68-11e9-9a71-cb8555a9e3fd.png)

If what you want was to show 5 of **LOADED EVENTS**, use `slotCounts`. 
![image](https://user-images.githubusercontent.com/1720610/66736435-71d0d900-ee69-11e9-9058-2a6aaf862504.png)

**Comment by eouia** [comment]
![image](https://user-images.githubusercontent.com/1720610/66758017-b7a79480-ee9d-11e9-91d6-9598a6e5f66b.png)
Well, I'm using your config and there seems nothing wrong.
Are you using page-changing/sliding or show/hide controlling module together with this module?

**Comment by Lotusvball** [comment]
No I am not.  that is very interesting.  So then there is nothing wrong with the code.  Thanks.

**Comment by MerlijnAlmer** [comment]
@Lotusvball are you sure you installed it correctly because thats also a thing i did wrong to at first. i did start with javascript and css 2 months ago.

>"cd ~/MagicMirror/modules
git clone --depth=1 https://github.com/eouia/MMM-CalendarExt2
cd MMM-CalendarExt2
npm install"

**Comment by Lotusvball** [comment]
Are there any log files I can look at to see what is going on.  

I am getting this in the terminal:

Connecting socket for: MMM-CalendarExt2
Sockets connected & modules started ...
Launching application.
[CALEXT2] calendar:Steve >> Scanning start with interval:1800000
[CALEXT2] calendar:Steve >> Scanned: 35, Selected: 35


But nothing.  I have commented out all other modules.

**Comment by Lotusvball** [comment]
> @Lotusvball are you sure you installed it correctly because thats also a thing i did wrong to at first. i did start with javascript and css 2 months ago.
> 
> > cd ~/MagicMirror/modules
> > git clone --depth=1 https://github.com/eouia/MMM-CalendarExt2
> > cd MMM-CalendarExt2
> > npm install

I will try again just to make sure.

**Comment by Lotusvball** [comment]
What does this mean?

created a lockfile as package-lock.json. You should commit this file.

**Comment by eouia** [comment]
@Lotusvball
If you are using `pm2` to manage MM process, first stop it.
Then, go to MagicMirror directory then try this;
```
npm start dev
```
It will show you the front-dev panel on your MM screen. (usually right side)
Then naviage to `console` tab of that panel. If you find some error(by red color), report me.

**Comment by Lotusvball** [comment]
I used npm start dev and I see not error and I now see the calendar.  

When I use this to start it I see nothing still:
cd ~/MagicMirror && DISPLAY=:0 npm start

Is there an issue with this command?

**Comment by Lotusvball** [comment]
I just started it using pm2 start MagicMirror and no Calendar.

**Comment by Lotusvball** [comment]
Not sure what changed, but I am now seeing the calendar.  Thanks for your patience.  Very strange.

**Comment by Lotusvball** [comment]
I do have one more question if you don't mind.  What does the (an hour) mean?

**Comment by eouia** [comment]
Maybe you need some delay to show the calendar. the interval of drawing and the interval of parsing are independent so, if your parsing is not finished on drawing time due to slow connection or too many events to parse, you cannot see anything. (It will be refreshed on next drawing interval)
To avoid this, you can use `firstDrawingDelay`. you can give some delay before drawing first time to finish parsing calendars.
https://github.com/eouia/MMM-CalendarExt2/wiki/2e.-Configuration:Others

And..
`(an hour)` is a duration of events. Read this document also
https://github.com/eouia/MMM-CalendarExt2/wiki/Event-Time

**Comment by Lotusvball** [comment]
Great.  Thanks so much.

**Comment by redy** [comment]
Hi, I seem to be having a similar issue. I followed the installation directions and the fix suggestions described in this issue. 1. Reinstall plugin 2. start in dev mode 3. Increase firstDrawingDelay. I see nothing on the screen (i am able to see other modules).


I have this as my config.

			module: "MMM-CalendarExt2",
			config: {
				 rotateInterval: 90*1000,
				 firstDrawingDelay: 1000*10,
				 scenes: [ // `scenes` could have several scenes as elements of array
				 {
					   name: "My kids schedule",
					   views: ["Daily", "Weekly"],
					   //className: "CX2",
				 },

				],
				views: [
					{
					  name: "Daily",
					  mode: "upcoming",
					  calendars: ["Schedule"],
					  position: "top_center",
					  maxItems: 5,
					  maxDays: 1,
					  locale: "en",
					  hideOverflow: false,
					  filterPassedEvent: true,
					},
					{
					  name: "Weekly",
					  mode: "weekly",
					  position: "middle_center",
					  calendars: ["Schedule"],
					  type: "row",
					  slotCount: 5,
					  locale: "en",
					  hideOverflow: false,
					  filterPassedEvent: true,
					},
				  ],
				  calendars : [
					{
					  name: "Schedule",
					  icon: "noto-soccer-ball",
					  url: "https://calendar.google.com/calendar/ical/1d4a1djtgmai0fpapjvtr6cdhs%40group.calendar.google.com/public/basic.ics",
					  //url: "webcal://p23-caldav.icloud.com/published/2/MTU3Mzc5NzU3MTU3Mzc5N7QDyWhkoQhUDUPID--ipr-ZOrn-Q4_1aVyt-0MWrJp7YNRJozQcvp5txgCkR1Oa9aPtBd5BXqQ48ly68Sx7T98/"
					},
				  ],

			},
			  },

Help appreciated.
