### ISSUE TITLE
replaceTitle on time

### ISSUE THREAD

**Issue by MerlijnAlmer** [eouia/MMM-CalendarExt2#33]
it's more of a question i have but i am trying to change some of the titles of the calendar based on name+time instead of only name because multiple diffrent events have the same name. the way that could work i because we the event happens on the same time each time the name needs to be the same. the way i thought it could work was doing this↓ but i don't know what i am doing could someone help.

> "transform:(event) => {
      if (event.startDate < ((10:30))) {
      replaceTitle: [ ["Alex de Jong", "Teammeeting"],
      }
      return event
      }, "

**Comment by eouia** [comment]
Sorry,  I think you(or at least one of your colleagues) need to know basic Javascript to handle full features. 
I understand what you want, and it is fully possible with this module, but I'm not one of your IT section staff.
