### ISSUE TITLE
Date format for first date and first day of month differ from others

### ISSUE THREAD

**Issue by dberntsson** [eouia/MMM-CalendarExt2#35]
Having config:
                                views: [
                                  {
                                        mode: "week",
                                        position: "middle_center",
                                        dateFormat: "D",
                                  },
                                ],

Result:
![IMG_20191031_224002](https://user-images.githubusercontent.com/9644179/67989527-5c162e80-fc33-11e9-8bc6-175f5fb299be.jpg)

Expecting:
Having the same dateformat on every date header.

**Comment by eouia** [comment]
set `slotAltTitleFormat: "D",`.
