### ISSUE TITLE
Support for multi-line in event

### ISSUE THREAD

**Issue by dberntsson** [eouia/MMM-CalendarExt2#38]
views: [
        {
          mode: "week",
          position: "middle_center",
        },
      ],

Every event in this view looks like this:
* "starttime a long ti...."

I would like to have event-start-time and event-end-time on one row, and event title on a separate row.
Is that possible?

**Comment by eouia** [comment]
`week` and `month` view don't support multi-line. MM screen is too small to display whole things. I regard these views as a summary or overview.
