### ISSUE TITLE
Request: Week view from today, not Mondays (or Sundays)

### ISSUE THREAD

**Issue by mabahj** [eouia/MMM-CalendarExt2#39]
Hi,

Great module! Thank you very much for sharing and maintaining this. It is the single most important item on my screen.

I have a humble feature request, that I was hoping you may consider: The week view shows the current week, starting from Mondays (or Sunday, depending on the locale). That means that I have to show 2 weeks to be able to see what's next on Sunday. If it was possible to "show the week from today", i.e. the next 7 days, then we would save screen real estate. The daily view sort of shows this, but vertically, not horizontally.

I've been looking at the code to see if I could make a PR or implement a hack for myself, but it is unfortunately too complicated for me.

**Comment by eouia** [comment]
`Daily` view can be used horizontally
![image](https://user-images.githubusercontent.com/1720610/68925133-b0b4c000-0782-11ea-8bd2-b8e4a9e0e69e.png)
```js
slotCount: 6,
type: "row",
```

However I'll consider your suggestion.

**Comment by mabahj** [comment]
Ah! Nice! I now see there's a lot more documentation in doc/Configuration/Views. I completely missed any links to those chapters when I configured my calendar. The "row" configuration works very well for me. Thanks again!
