### ISSUE TITLE
Use the space better

### ISSUE THREAD

**Issue by dberntsson** [eouia/MMM-CalendarExt2#40]
Is it possible for the events to "wrap" and use the whole width as two columns?

![IMG_20191115_002835](https://user-images.githubusercontent.com/9644179/68904894-6eb65a80-073f-11ea-86f8-fcca18067489.jpg)

**Comment by eouia** [comment]
![image](https://user-images.githubusercontent.com/1720610/68924532-5a934d00-0781-11ea-9208-724c4f24fe21.png)
I think this would be the reason. adjust it in your `css/custom.css`

**Comment by dberntsson** [comment]
I changed max-row-width without better result.
I want two columns in every slot.
