### ISSUE TITLE
invalid line (no token ";" or ":") (Nextcloud ics)

### ISSUE THREAD

**Issue by giddyhup** [eouia/MMM-CalendarExt2#41]
When I try to use a Nextcloud hosted calendar I get this error in the node log:
`
invalid line (no token ";" or ":") "<?xml version="1.0" encoding="utf-8"?>"`

The same calendar works with MMM-CalendarExt

Config example:

 ```
       {
            module: 'MMM-CalendarExt2',
            position: "top_bar",
            config: {
              calendars : [
              {
                   name: "Demo",
                    url: "https://example.com/remote.php/dav/calendars/family/john?export",
                    auth: {
                        user: "john",
                        pass: "XXXX",
                        method: "XXXX"
                    }
                }
            ],
              views: [
                {
                  mode: "daily",
                },
              ],
              scenes: [
                {
                  name: "DEFAULT",
                },
              ],
            },
          },
```

**Comment by eouia** [comment]
Hmmm... that case will happen when the URL was wrong(or a result of your auth is wrong). Without real ical data, I cannot inspect what was the problem.

**Comment by giddyhup** [comment]
Thanks for the quick response. I am afraid I can't share the private calendar but I am testing with MMM-CalendarExt2 and MMM-CalendarExt in the same config with the same URL and MMM-CalendarExt fetches the data without issue (both modules were installed today on a fresh install of MagicMirror).

```
[CALEXT2] calendar:Demo>> Scanning start with interval:1800000
[CALEXT] https://example.com/remote.php/dav/calendars/family/john?export  >> Fetch starts.
[CALEXT2] calendar:Demo>> invalid line (no token ";" or ":") "<?xml version="1.0" encoding="utf-8"?>"
[CALEXT] https://example.com/remote.php/dav/calendars/family/john?export  >>
{ state: 'renewed',
  lastFetchedTime: '19-11-15 13:39:04',
  lastFetchedEvents: 12,
  lastFetchedOldEvents: 11,
  lastServedEvents: 23,
  error: null }

```

**Comment by eouia** [comment]
Two modules are using different parser. (CX2 uses better but somewhat strict)
`invalid line (no token ";" or ":") "<?xml version="1.0" encoding="utf-8"?>` says there is some invalid format in your ics parsing result. But I have no idea unless look inside the real data. sorry.

**Comment by eouia** [comment]
I've fixed it. update and try again. 

![image](https://user-images.githubusercontent.com/1720610/68957429-4d4e8080-07ca-11ea-8852-d29cc98725af.png)


![image](https://user-images.githubusercontent.com/1720610/68957465-62c3aa80-07ca-11ea-87bd-afbb04f611ac.png)

**Comment by giddyhup** [comment]
Thanks!

**Comment by katerasrael** [comment]
I have the same issue with a Nextcloud calendar - fresh install of magicmirror and the module. Do you have any hints how to fix the error?

**Comment by katerasrael** [comment]
"Fixed" it myself - i forgot to specify the authorization...
