### ISSUE TITLE
no auth mechanism defined

### ISSUE THREAD

**Issue by dberntsson** [eouia/MMM-CalendarExt2#42]
With latest code the calendars won't show.
I have public Google ics files defined without the need nor config for auth.
Readme same as yesterday, so no new configuration needed I guess based on today commit.

git log
commit ee516dc7e6e04ed028fc76d187e2dd2ad80540f7
Author: eouia <eouia0819@gmail.com>
Date:   Fri Nov 15 17:05:30 2019 +0100

    fix:auth not working

npm start
[CALEXT2] calendar:Daniel >> Scanning start with interval:120000
[CALEXT2] calendar:Daniel >> no auth mechanism defined

in commit 438eb5dd9408e9a4c546155d87fc13b5ba4cc2fc it just says:
[CALEXT2] calendar:Daniel >> Scanning start with interval:120000

Same error result in:
commit bb86004ae02c35bcd7071c22f5e2e5e3a0a07e09
Merge: a50c9ad 3dbc862
Author: eouia <eouia0819@gmail.com>
Date:   Fri Nov 15 16:58:38 2019 +0100

    Merge branch 'master' of https://github.com/eouia/MMM-CalendarExt2

commit a50c9adcca668513085ca2b87ac84db54d9c9f10
Author: eouia <eouia0819@gmail.com>
Date:   Fri Nov 15 16:58:24 2019 +0100

    fix:auth not working

commit f21b1d099c2c8c2b55065c5790608ad544776692
Merge: b42132f 7201ba9
Author: eouia <eouia0819@gmail.com>
Date:   Fri Nov 15 16:50:47 2019 +0100

    fix:auth not working

commit b42132fa677c97802c74249a578a13de7493ba6b
Author: eouia <eouia0819@gmail.com>
Date:   Fri Nov 15 16:48:25 2019 +0100

    fix:auth not working

commit 438eb5dd9408e9a4c546155d87fc13b5ba4cc2fc .  **(WORKS HERE!!!!)**
Author: eouia <eouia0819@gmail.com>
Date:   Fri Aug 23 12:52:22 2019 +0200

    1.0.5:add name of month in month view

**Comment by eouia** [comment]
Sorry, Yesterday I fixed something but it made another bug. I fixed it now.

**Comment by dberntsson** [comment]
Fixed with last auth commit 2019-11-16
