### ISSUE TITLE
MMM-CalendarExt2  & MMM-Page-Selector not working together. 

### ISSUE THREAD

**Issue by tars01** [eouia/MMM-CalendarExt2#43]
I seem to be having an issue with MMM-CalendarExt2 working together with MMM-Page-Selector. All other modules I have work fine with MMM-Page-Selector but when I try use Ext2 there is just a blank screen where I should have the calendar showing.  I am able to get Ext2 running fine on it's own. 

I have attached my Ext2 config as it won't embed. 
[ext2.txt](https://github.com/eouia/MMM-CalendarExt2/files/3870237/ext2.txt)

There is nothing obvious showing in pm2 logs and developer console.

I have also posted over in the MM forums and there is another user having the same issue.

[https://forum.magicmirror.builders/topic/11635/config-js-example-of-mmm-page-selector-mmm-calendarext2-working-together](url)

Thanks

**Comment by eouia** [comment]
You have 4 options.
1) Put the calendar on the first page.
2) Put the calendar on all pages, and control its scene order by notifcation from Page module.
https://github.com/eouia/MMM-CalendarExt2/wiki/3.-Usage#user-defined-notification-trigger
3) Set the `rotateInterval`(or `updateInterval`, depends on how you use scenes) enough shortly.
4) Or just wait refreshing calendar (but when your page changing interval is somewhat short, it won't work)


This symptom would happen when the interval of page changing and that of refreshing calendar both are mismatched.

**Comment by tars01** [comment]
Thanks, let me try this.

**Comment by golden-oldie** [comment]
Hi,

I've tried option 1 but that's not working.
Also tried amending timers as suggested in 3 and 4 but no joy. 

I've pasted the code below. Am I missing something obvious here?

	modules: [
    {
        module: "MMM-Page-Selector",
        position: "top_bar",
        config: {
            defaultPage: "PageOne",
            displayTitle: true,
            autoChange: {
                interval: 60
            }
        }
    },
        {
        module: "clock",
        position: "top_right",
        pages: {"PageOne": "top_right","PageTwo": "top_right"},
        config: {
                displaySeconds: false,
                },
        },

        {
        module: 'MMM-CalendarExt2',
        config: {
                rotateInterval: 0,
                updateInterval: 60*1000,
                calendars : [
                                {
                                name: "Meeting room",
                                url: "https://outlook.live.com/owa/xxxxx
                                beforeDays: 6,
                                afterDays: 6,
                                scanInterval: 600*100
                                },
                        ],
                views: [
                        {
                                mode: "daily",
                                slotCount: 1,
                                pages: {"PageOne": "top_left"},
                                calendars: ["Meeting room"],
                        },
                        ],
                        scenes: [
                                        {
                                        name: "DEFAULT",
                                        },
                                ],
                },
        },
        ]
	};

**Comment by tars01** [comment]
This does not work for me either. Any suggestions welcome.

**Comment by golden-oldie** [comment]
I've now tried using the page notification method and this doesn't work either. Real shame as this is a really great module if it would just work with "MMM-Page-Selector" 

@eouia - are you able to assist please?

**Comment by eouia** [comment]
If you don't mind front-end temporal error log, you can just use it like;
```js
  {
    module: 'MMM-CalendarExt2',
    pages: {"PageOne": "temp"},
    config: {
```

**Comment by eouia** [comment]
If you have several Scenes per page, it needs another approach, but in your above example code, that is enough.

**Comment by GattoJohnny** [comment]
Once I had the same problem. Placing MMM-Page-Selector "fullscreen_above", and MMM-CalendarExt2 "top_bar" solved the case for me. You may want to give it a try.
