### ISSUE TITLE
Control Days to show in Month View

### ISSUE THREAD

**Issue by isaacrlevin** [eouia/MMM-CalendarExt2#44]
I want to be able to show maybe 2 weeks of events in month view. How would I go about doing that.

**Comment by eouia** [comment]
??? i can't catch your words. tell me more details. even some pics could be help

**Comment by isaacrlevin** [comment]
For instance in V1 of CalendarExt, we could do this

````
					daily: {
						position:
							"bottom_bar",
						timeFormat:
							"h:mm A",
						counts: 5
					},
````

And that would show a month view, but only 5 days, I am looking for that. I like the time format

**Comment by eouia** [comment]
You mean just to show 5 days (From Monday to Friday) in table view? Like this?
![image](https://user-images.githubusercontent.com/1720610/70304587-8fd00f80-1802-11ea-8fdc-49f7930eaa5d.png)
```
views: [
  {
    title: "1 Week View",
    name: "VIEW1",
    mode: "week",
    calendars: [],
    position:"bottom_bar",
    slotMaxHeight: "120px",
    showWeekends: false,
    slotCount: 1,
  },
],
```

**Comment by isaacrlevin** [comment]
that worked great, would be really nice to show different config examples
