### ISSUE TITLE
only 3 events

### ISSUE THREAD

**Issue by SARCux** [eouia/MMM-CalendarExt2#45]
Hi,
i can´t find the problem.
i don`t see more then 3 event :-(
Where is the problem???

Can u help me??? PLEASE

![2019-12-07 20_36_57-192 168 178 57 (raspberrypi) – VNC Viewer](https://user-images.githubusercontent.com/29655415/70379787-6f52a300-1931-11ea-90a2-e08b292596d7.png)

**Comment by eouia** [comment]
No problem at all. Just set the `slotMaxHeight` bigger.
https://github.com/eouia/MMM-CalendarExt2/wiki
