### ISSUE TITLE
how to make view title show month and year

### ISSUE THREAD

**Issue by sdetweil** [eouia/MMM-CalendarExt2#47]
I have two views in my scene. one centered and the other lower_right

I want the title over them to be the month and year (like December 2019, and then January 2020

the current thing puts the module-header there, but no distinction on which is which (I would have thought it would have the view name attached so I could set the style of that header..
but haven't found how to make the text dynamic  (some algorithm to format the month/year)

[screenshot](https://www.dropbox.com/s/h52v02rgp0hz9iq/Screenshot%20from%202019-12-11%2011-35-30.png?dl=0)

**Comment by sdetweil** [comment]
for class access in calext2_view.js 

```
    if (this.config.title) {
      var header = document.createElement("header")
      header.classList.add("module-header")
      if (this.config.className) header.classList.add(this.config.className)  //< --- add this line after 130 
```

**Comment by sdetweil** [comment]
for the header text content, i need it to change dynamically, so some function executed on each refresh returns the string to be used

**Comment by eouia** [comment]
`month` view has its own dynamic view title. ('monthFormat') but not as `module title`.
I'll consider callback function to change `module title` on runtime. 
Thanks for suggestion. I'll add this feature on next week.

**Comment by eouia** [comment]
I've updated. Now `title` can have a callback function to return contextual title text.
```js
title: (mObj) => { // arguments as `moment` object of first slot starting time.
  return mObj.format("[My Weekly:] Wo")
}
```
