### ISSUE TITLE
need documentation of html elements in each view

### ISSUE THREAD

**Issue by sdetweil** [eouia/MMM-CalendarExt2#48]
when I want to create a css entry for a particular element of a view (center title of month view for example),
I have to use the debugger to navigate the elements to determine what class u assigned each element

is there a doc with a table that shows all the elements of each view style

**Comment by eouia** [comment]
Sorry for the inconvenience.
Ref these;
https://github.com/eouia/MMM-CalendarExt2/wiki/4.-Styling

Due to my English level, to make a detailed guide is not so easy. Would you help me?

**Comment by sdetweil** [comment]
i will try when I have time.. this is styles.. but  I want to know where the classes are used..

I am having trouble.  right now.. month view, want either the title or altTitle centered over the day on each cell.. 

but can't figure it out.. i am looking in the developers window elements view. 

there is a slotHeader for each row, but it is not used
then there is a slotHeader for each slotContent for each cell which is used
but if I change the style, it affects all rows (except the first)

I can turn off the subTtitle (sun/mon/tue), and I can show the altTitle 12/5, 12/6, but I cannot center it. 

and it looks like I have to have a css element for every cell.  instead of once for view.

**Comment by eouia** [comment]
Do you mean this?
![image](https://user-images.githubusercontent.com/1720610/70719582-8e1ab600-1cf2-11ea-8f93-5bab12ce000f.png)


css/custom.css
```css
.CX2 .cellSlot .slotHeader {
  flex-direction:row;
  justify-content:center;
}

.CX2 .weekSlot.seq_0 .cellSlot .slotSubTitle {
  display:none;
}
```

config.js
```js
slotTitleFormat: "MM/DD dd"
```

I didn't change AltTitle inentionally to see the difference. Of course, you can modify it also for your needs.

**Comment by sdetweil** [comment]
yes but , why does

.CX2 .**weekSlot.seq_0** .cellSlot .slotSubTitle {
  display:none;
}
change for all rows?

**Comment by eouia** [comment]
Not for all rows. Originally `.CX2. weekSlot .cellSlot .slotSubtitle` have haven `display:none`. Only `weekSlot.seq_0` had `display:block`, but now it become hidden like other rows. So it doesn't change all rows.
