### ISSUE TITLE
Google calendar look

### ISSUE THREAD

**Issue by GattoJohnny** [eouia/MMM-CalendarExt2#49]
I wonder if you have any plans to add a proportional (vertical timeline) look of the module? Something like MMM-Timetable with dynamic data.

**Comment by eouia** [comment]
I cannot understand what you mean. Is there any sample picture?

**Comment by GattoJohnny** [comment]
Sure. Now my calendar looks like this (week view):

![20191212-MMM-CalendarExt2-01](https://user-images.githubusercontent.com/47010649/70714116-c5379a00-1ce7-11ea-9981-6ceb4ee6395e.jpg)

Desired arrangement would be like this (taken from Google Calendar):

![20191212-MMM-CalendarExt2-02](https://user-images.githubusercontent.com/47010649/70714187-e6988600-1ce7-11ea-8863-ec815efcffcd.jpg)

Your MMM-Timetable module displays data in a vertical timeline view, similar to the desired arrangement, that's why I asked if you have any intention to implement that layout to my favorite calendar module, MMM-CalendarExt2...

I was considering the MMM-CalendarExtTimeline plugin, which is great, but that can deal with one single day only.

**Comment by eouia** [comment]
Frankly, I'd considered that kind of view, but too complex to implement. Anyway, I'll consider it in the future.
