### ISSUE TITLE
Calendar stops synching

### ISSUE THREAD

**Issue by mdelapaz** [eouia/MMM-CalendarExt2#51]
Occasionally, I'll get an error similar to the following when a calendar tries to sync:

[CALEXT2] calendar:1 >> getaddrinfo EAI_AGAIN calendar.google.com calendar.google.com:443

After this point, the module stops trying to sync that particular calendar forever (until a restart).  This is generally a transient error and it would be nice if the module would either retry the sync immediately or at the very least, try it again the next time the scanning interval comes around.

**Comment by eouia** [comment]
I'll consider.

**Comment by cskenney** [comment]
I am experiencing the same error and unfortunately you can't tell the error is occurring unless you monitor the logs.

**Comment by eouia** [comment]
`EAI_AGAIN` is a DNS lookup timed out error, means it is a network connectivity error or proxy related error temporally or permanently. In that case, you need to check your network status first.
And in that case, CALEXT2 will try to connect and scan the cal url on next scanInterval automatically. (I think so, doesn't it work like that?)

**Comment by cskenney** [comment]
From my experience once the error occurs CALEXT2 will not try to scan that url again.  It seems to error out.  I have 7 calendars that are being scanned.  They are all Google calendars and are being scanned at the same interval.  If I monitor the log file I will get the EAI_AGAIN error on one of the calendars but the others will still be scanned.  The url with the error is never scanned again.  After a period of time I may get the same error on a different url.  Again it will no longer scan that url.

While searching for why this may happen the first thing that comes up is a network issue.  However, even if that occurred it should be a problem for all the calendars or it should be able to auto recover.  I also read that too many requests to Googles site may also cause this issue but I can't confirm it.  I was doing troubleshooting on my calendars and had the scan interval set to every 60 seconds.  As time went on leaving it like this it seemed like I started to get this error more frequently.  I reduced my scan interval and have not seen the error.  One person assumed there may be quoto per month of requesting data from Google calendar and this error may be in response to exceeding the quota.  I can not find any data to support that idea though.

**Comment by eouia** [comment]
I've never heard URL connection quota or limitation. iCal url is not a kind of API.  Maybe too many connections would be the reason, but I don't agree there be an explicit restriction though.
To set a different interval would be a good approach.

Anyway, I modified to rescan even on error. update and tell me the result.

**Comment by mdelapaz** [comment]
That fix is essentially the same change I made locally, and it's been working fine.
