### ISSUE TITLE
scene rotation problem

### ISSUE THREAD

**Issue by GattoJohnny** [eouia/MMM-CalendarExt2#52]
I started to utilize the scene rotation feature, and came accross something I cannot solve myself.

There are 3 pages on my mirror ("page1", "page2", "page3"), MMM-Page-Selector rotates them, MMM-Button sends the trigger sign. According to the Wiki I added the "PAGE_CHANGED" snippet to the notifications section of MMM-CalendarExt2.js file.

With 3 scenes ("DEFAULT", "scene2", "scene3"), each page containing 1 scene, everything works fine:
- "DEFAULT" scene on "page1"
- "scene2" on "page2"
- "scene3" on "page3"
- "DEFAULT" scene on "page1" again, etc. 

So far so good. But I want to have the 3rd page without any calendars, and it gives me a headache. 

Deleting "scene3" from the config file results in:
- "DEFAULT" scene on "page1"
- "scene2" on "page2"
- "page3" without calendars, and then "scene2" stucks in like
- "scene2" on "page1"
- "scene2" on "page2"
- "page3" without calendars
- "scene2" on "page1"
- "scene2" on "page2", etc.

Please advise.

**Comment by eouia** [comment]
How about assigning a fake scene/view with no event?

Or you can hide views of 3rd scene by CSS.

1. assign view `className` to the fake view to hide
2. Then in `css/custom.css`
```css
.CX2 .view.YOUR_VIEW_CLASSNAME_TO_HIDE {
  display:none;
}
```

**Comment by GattoJohnny** [comment]
Sean, your're great again.

Both suggestions work good. And, unintentionally, you gave me a hint. A view in week mode can have the slotCount parameter. "slotCount: 0" also hides the whole module.

But of all of them I prefer the CSS way. Thank you again for your excellent assistance. And have a prosperous new year! :-)
