### ISSUE TITLE
Error on loading script: modules/MMM-CalendarExt2//MMM-CalendarExt2.js

### ISSUE THREAD

**Issue by lunarose23** [eouia/MMM-CalendarExt2#54]
I'm having this issue. Let me know what info I can get you. 

loader.js:191 GET http://home-dak.herokuapp.com/modules/MMM-CalendarExt2//MMM-CalendarExt2.js net::ERR_ABORTED 404 (Not Found)
loadFile @ loader.js:191
loadModule @ loader.js:135
loadNextModule @ loader.js:29
(anonymous) @ loader.js:31
(anonymous) @ loader.js:125
(anonymous) @ loader.js:161
loadTranslations @ module.js:334
(anonymous) @ loader.js:158
loadNextDependency @ module.js:299
(anonymous) @ module.js:296
stylesheet.onload @ loader.js:200
load (async)
loadFile @ loader.js:199
loadFile @ loader.js:257
loadNextDependency @ module.js:294
loadDependencies @ module.js:303
loadStyles @ module.js:269
(anonymous) @ loader.js:156
loadNextDependency @ module.js:299
(anonymous) @ module.js:296
script.onload @ loader.js:184
load (async)
loadFile @ loader.js:183
loadFile @ loader.js:250
loadNextDependency @ module.js:294
(anonymous) @ module.js:296
script.onload @ loader.js:184
load (async)
loadFile @ loader.js:183
loadFile @ loader.js:250
loadNextDependency @ module.js:294
loadDependencies @ module.js:303
loadScripts @ module.js:278
bootstrapModule @ loader.js:154
afterLoad @ loader.js:124
(anonymous) @ loader.js:137
script.onload @ loader.js:184
load (async)
loadFile @ loader.js:183
loadModule @ loader.js:135
loadNextModule @ loader.js:29
(anonymous) @ loader.js:31
(anonymous) @ loader.js:125
(anonymous) @ loader.js:161
loadTranslations @ module.js:334
(anonymous) @ loader.js:158
loadNextDependency @ module.js:299
loadDependencies @ module.js:303
loadStyles @ module.js:269
(anonymous) @ loader.js:156
loadNextDependency @ module.js:299
loadDependencies @ module.js:303
loadScripts @ module.js:278
bootstrapModule @ loader.js:154
afterLoad @ loader.js:124
(anonymous) @ loader.js:137
script.onload @ loader.js:184
load (async)
loadFile @ loader.js:183
loadModule @ loader.js:135
loadNextModule @ loader.js:29
(anonymous) @ loader.js:31
(anonymous) @ loader.js:125
(anonymous) @ loader.js:161
(anonymous) @ translator.js:186
xhr.onreadystatechange @ translator.js:22
XMLHttpRequest.send (async)
loadJSON @ translator.js:25
load @ translator.js:180
loadTranslations @ module.js:331
(anonymous) @ loader.js:158
loadNextDependency @ module.js:299
(anonymous) @ module.js:296
stylesheet.onload @ loader.js:200
load (async)
loadFile @ loader.js:199
loadFile @ loader.js:250
loadNextDependency @ module.js:294
(anonymous) @ module.js:296
stylesheet.onload @ loader.js:200
load (async)
loadFile @ loader.js:199
loadFile @ loader.js:257
loadNextDependency @ module.js:294
loadDependencies @ module.js:303
loadStyles @ module.js:269
(anonymous) @ loader.js:156
loadNextDependency @ module.js:299
(anonymous) @ module.js:296
script.onload @ loader.js:184
load (async)
loadFile @ loader.js:183
loadFile @ loader.js:257
loadNextDependency @ module.js:294
(anonymous) @ module.js:296
script.onload @ loader.js:184
load (async)
loadFile @ loader.js:183
loadFile @ loader.js:257
loadNextDependency @ module.js:294
(anonymous) @ module.js:296
script.onload @ loader.js:184
load (async)
loadFile @ loader.js:183
loadFile @ loader.js:257
loadNextDependency @ module.js:294
loadDependencies @ module.js:303
loadScripts @ module.js:278
bootstrapModule @ loader.js:154
afterLoad @ loader.js:124
(anonymous) @ loader.js:137
script.onload @ loader.js:184
load (async)
loadFile @ loader.js:183
loadModule @ loader.js:135
loadNextModule @ loader.js:29
loadModules @ loader.js:46
loadModules @ loader.js:219
init @ main.js:457
(anonymous) @ main.js:584
loader.js:187 Error on loading script: modules/MMM-CalendarExt2//MMM-CalendarExt2.js

**Comment by eouia** [comment]
Well, What backend(server-side) log says?
