### ISSUE TITLE
Image links on Wiki are broken

### ISSUE THREAD

**Issue by Gordontgopher** [eouia/MMM-CalendarExt2#55]
I notice that some of the images on the wiki are not loading. It appears the links are broken.
For example:  on https://github.com/eouia/MMM-CalendarExt2/wiki/2c1.-View:daily  the image 'view1' is linked to https://github.com/eouia/MMM-CalendarExt2/raw/master/screenshot/view1.png . I believe the correct image is https://github.com/eouia/MMM-CalendarExt2/tree/master/doc/Configuration/Views/view1.png

Similar issues on configuration and all the view pages.

Thanks for a great module!

**Comment by eouia** [comment]
once I have moved the docs, but due to my laziness, i havent fixed the links, sorry. :)

**Comment by eouia** [comment]
fixed. Thanks for your report.
