### ISSUE TITLE
Month view starting from current week

### ISSUE THREAD

**Issue by AndrewSav** [eouia/MMM-CalendarExt2#57]
I would like to display several weeks, starting from current week, similar to "month" view, but avoiding going back to the beginning of the month.

Would you consider PR: https://github.com/AndrewSav/MMM-CalendarExt2/commits/add-weeks

**Comment by eouia** [comment]
what is main difference with current "week" view?

**Comment by AndrewSav** [comment]
Intention was to display more that one week.

**Comment by eouia** [comment]
Thanks for your contribution.
But `week` view already can have more than 1 week by `slotCount`.
![image](https://user-images.githubusercontent.com/1720610/74316881-a94d8480-4d7a-11ea-995d-351866be52d4.png)
Is it something different with yours?

**Comment by AndrewSav** [comment]
From documentation:

slotCount: "Only in daily, weekly, monthly, this field will be valid. In other view modes, this will be ignored."

From this we an deduce that slotcount is ignored on "week", since it's not daily, weekly or montly. Is this wrong?

**Comment by AndrewSav** [comment]
Okay, so I tried "week" and it kind of works. It probably has different styles though becase with "week" view it takes _much_ more space vertically. With more than 3 weeks it's especially noticeble. Is there a way to make "week" as compact as "month"?

**Comment by eouia** [comment]
set 'slotMaxheight'.

**Comment by AndrewSav** [comment]
Thank you. It worked. Would be nice if you could fix the doc. Will help the next poor soul.

**Comment by eouia** [comment]
Sorry for the inconvenience. I edited the contents. Thanks for your report and interest.

**Comment by AndrewSav** [comment]
Thank you for this. I do not see any recent changes in the `slotCount` documentation [here](https://github.com/eouia/MMM-CalendarExt2/blob/master/doc/Configuration/View.md) it still says:

>Only in daily, weekly, monthly, this field will be valid. In other view modes, this will be ignored.

This is the main reason I did not try it with "week" in the first place - the doc clearly said it would not work,

**Comment by eouia** [comment]
i changed in the wiki. 
some volunteer made docs folder and moved the contents into it but i thought no one will see that prior than online wiki.
to avoid misconception i'll remove docs folder tomorrow

**Comment by AndrewSav** [comment]
Great! Note that the _readme itself_ pointing to the doc folder you might want to fix the links in readme, as they become brocken if you remove the doc folder.

**Comment by eouia** [comment]
Yes, Hmmm... somewhat annoying situation. :)
I don't want to `git push` the docs whenever I need some docs modification. But a PR from a good samaritan made all wiki to move into docs folder. I accepted it without deep thought. That makes me somewhat embarrassed at this moment...
