### ISSUE TITLE
MMM-CalendarExt2 dosn`t work with MMM-pages

### ISSUE THREAD

**Issue by Skorpionbird** [eouia/MMM-CalendarExt2#6]
Hello
I have a the following issue.  I use the MMM-pages Modul and when i set the MMM-CalendarExt2 Modul to permant show then it works. But when i say the MMM-CalendarExt2 is on page 2 as example then i cant see the Calendar, i see just a black page.  i tried with other modules on the same page and this is working with no problems.
Any help out there?
Skorpionbird

**Comment by eouia** [comment]
MMM-CalendarExt2 needs the time to measure area dimension to draw calendars. So if CalendarExt2 is not drawn at start, it would not know the position and size where should be displayed. Anyway, It will be drawn in `updateInterval` or `rotateInterval` finally. Set the values shorter.
Or, you can put this module the first page at start, then hide it. Once it measure the dimension, it can be displayed in other pages also.

**Comment by eouia** [comment]
Anyway, I've updated for you. Now it could be visible after second page.

**Comment by Skorpionbird** [comment]
Thank you so much. It works now perfect.
