### ISSUE TITLE
config option for "show weeks" to disable weeksmark

### ISSUE THREAD

**Issue by DanielNagy** [eouia/MMM-CalendarExt2#60]
Please create config item to be able to disable the week in week mode.

**Comment by eouia** [comment]
What it means `the week`? Picture will be a help

**Comment by DanielNagy** [comment]
i did this instead

```
.CX2 .weeksmark {
  visibility: hidden;
}
```

**Comment by eouia** [comment]
That's the right approach. I made everything controllable by CSS  as possible as I can.

**Comment by eouia** [comment]
Instead `visibility: hidden`, I think `display:none` would be better.

**Comment by DanielNagy** [comment]
Noted, Thanks. The more I have been digging into this, the more i noticed i need to brush up on my CSS Skills :)
