### ISSUE TITLE
Hiding the calendar completely isn't documented / working

### ISSUE THREAD

**Issue by berlincount** [eouia/MMM-CalendarExt2#61]
Hi,

thanks or this great software :)

But - I haven't found a way to hide it completely (I'm using `MMM-ProfileSwitcher` and MMM-OnScreenMenu` together, with `MMM-ProfileSwitcher` using a timer to switch back to the default view) ...

`MMM-CalendarExt2` ignores being hidden (which it shouldn't, imho!) and also doesn't really allow scenes that don't have any views in them (which would be an alternative).

CSS allows some way of accomplishing this, but that still means the DOM contains all objects and all calendar fetchers etc are running, all rendering is happening, etc ...

I think that if the module is hidden none of that should happen.

Thanks!

   count

**Comment by eouia** [comment]
Hmmm.. This module also respect `.hide()` and `.show()` convention of MM. 
https://github.com/eouia/MMM-CalendarExt2/blob/b05ab5293d221aef191da196d248e85656ac2004/MMM-CalendarExt2.js#L245-L259

so by just calling `hide()`, all views could be hidden. If not work, As far as I experience, most cases were `lockstring` priority issues. 

To hide/reveal specific views per page or profile(if status could be detectable by notification), you can compose scenes per page then rotate them by [notification](https://github.com/eouia/MMM-CalendarExt2/wiki/3.-Usage#user-defined-notification-trigger).

**Comment by berlincount** [comment]
Hmm. How can I figure out/debug logstring issues?
I've tried using Notifications, but something is going wrong there, at least when using timers per https://github.com/tosti007/MMM-ProfileSwitcher#configuring-timers -

```
  modules: [
    {
      module: 'MMM-ProfileSwitcher',
      config: {
        enterMessages: false,
        leaveMessages: false,
        timers: {
          'Calendar': {},
          'Control': {},
        }
      }
    },
[..]
    {
      module: "MMM-CalendarExt2",
      config: {
        calendars: [
          {
            icon: 'calendar',
            name: 'Mirror',
            url: 'http://REDACTED/mirror.ics',
          },
          {
            icon: 'calendar-times',
            name: 'Feiertage',
            url: 'https://calendar.google.com/calendar/ical/de.german%23holiday%40group.v.calendar.google.com/public/basic.ics'
          },
        ],
        views: [
          {
            name: "week",
            mode: "week",
          },
          {
            name: "none",
            mode: "daily",
            slotCount: 0,
          },
        ],
        scenes: [
          {
            name: "Calendar",
            views: ["week"],
          },
          {
            name: "Control",
            views: ["none"],
          },
          {
            name: "default",
            views: ["none"],
          },
        ],
        notifications: {
          "CHANGED_PROFILE": {
            exec: "changeSceneByName",
            payload: (payload) => { console.log("XXX"); console.log(payload.to); console.log("YYY"); return payload.to }
          }
        },
      },
      classes: 'Calendar'
    },
[..]
    {
      module: 'MMM-OnScreenMenu',
      position: 'bottom_right',
      config: {
        touchMode: true,
        menuItems: {
          /*
          notify0: {  title: "Default",
                                    icon: "undo",
                                    notification: "CURRENT_PROFILE",
                                    payload: "default" },
          */
          notify1: {  title: "Calendar",
                                    icon: "calendar",
                                    notification: "CURRENT_PROFILE",
                                    payload: "Calendar" },
          notify2: {  title: "Control",
                                    icon: "calculator",
                                    notification: "CURRENT_PROFILE",
                                    payload: "Control" },
          openDevTools: {  title: "DevTools",
                                    icon: "crosshairs"},
          refresh: { title: "Refresh MagicMirror", icon: "refresh", source: "ALL" },
        },
        enableKeyboard: true,
      },
      classes: 'default everyone'
    },
```

It seems like https://github.com/eouia/MMM-CalendarExt2/blob/master/CALEXT2_Scene.js#L17 is being called twice when the automatic timer hits and sends back to the "default" profile, maybe that's causing trouble?

How would I debug `lockstring` issues?

**Comment by eouia** [comment]
Personally I'm not using ProfileSwitcher and OnScreenMenu.
I'll try to install ProfileSwitcher and inspect what happens.

**Comment by berlincount** [comment]
Thanks for the assistance :) I have limited experience with the MMM code (yet), and keep on tossing in `console.log()` mostly ;)

**Comment by eouia** [comment]
console.log is real magic tool. I'm also dependent to it.

Anyway, I've installed https://github.com/tosti007/MMM-ProfileSwitcher now then tried this configuration.
```js
{
  module: 'MMM-ProfileSwitcher',
  config: {
    defaultTime: 10000,
    timers: {
      'default': {
        profile: "Calendar"
      },
      'Calendar': {
        profile: 'default',
      },
    }
  }
},
```
Set `clock` as `default` and CALEXT2 as `Calendar`. (Not test OnScreenMenu, I have no touch input at this moment, but I think enough to prove the module's working.)

<img width="1259" alt="cal1" src="https://user-images.githubusercontent.com/1720610/76091458-e265c700-5fbd-11ea-9081-5570299f7d58.png">

<img width="1255" alt="cal2" src="https://user-images.githubusercontent.com/1720610/76091467-e85ba800-5fbd-11ea-928a-328bbc9a612e.png">

**Comment by berlincount** [comment]
Hm. I wonder what's different in my setup.

I can switch to the Calendar view (and see the calendar), and the automatic switch back doesn't remove the calendar. No idea whether `enterMessages: false, leaveMessages: false,` make a difference.

You can use the OnScreenMenu via Keyboard, use the key left of the right ctrl key to open and then the cursor keys and return.

I wonder what oddity I configured there 🤔 ..

If you say show/hide should be respected anyway - how can I debug why it isn't?

**Comment by eouia** [comment]
Hmmm....
```
{
    module: 'MMM-OnScreenMenu',
    position: 'top_left',
		classes: "default everyone",
		config: {
        touchMode: true,
        menuItems: {
            refresh: { title: "Refresh MagicMirror", icon: "refresh", source: "LOCAL" },
        },
        enableKeyboard: true,
    }
},
```

I don't know this is your wants but anyway, I can get these screens.

<img width="1232" alt="cal3" src="https://user-images.githubusercontent.com/1720610/76093459-48078280-5fc1-11ea-94bf-a74cd294dc58.png">


<img width="1237" alt="cal4" src="https://user-images.githubusercontent.com/1720610/76093419-34f4b280-5fc1-11ea-8c76-34510ac6232a.png">

**Comment by berlincount** [comment]
Can you try:

- a default screen without calendar
- menu item that allows you to switch to a screen with a calendar
- a timer that switches you back to the default screen

.. in my case, the calendar then stays active.

**Comment by eouia** [comment]
https://www.dropbox.com/s/d7vikdwcsruszmd/temp.mov?dl=0

I made 3 pages (default -> another -> calendar -> back to default) then I tried in default page activate the menu. screen jumps to calendar directly then back to default without issue.

**Comment by berlincount** [comment]
Super odd.

**Comment by berlincount** [comment]
I've sent you something per Mail directly. If you've got any idea how to debug further, any ideas are welcome. I might have to try and get to a minimal config that exposes the bug, or it might be an artifact of the specific revisions I'm running (but should be :latest and master in all cases, no dev versions).

**Comment by bugsounet** [comment]
hi, I found a bug with CExt2 hidding/showing.

maybe it's a MagicMirror Core bug ...
@eouia is working around, please wait ;)

**Comment by rubenix** [comment]
ok maybe its related to my post [here](https://forum.magicmirror.builders/topic/11568/hi-there-is-a-new-alexa-module/76) 

Im trying to find an answer but cannot find a solution... @eouia can you please check that out and see if its related (config on my posts) im not a coder and im learning by myself 

thanks so much in advanced

**Comment by berlincount** [comment]
This is issue is gone in the latest version! \o/
