### ISSUE TITLE
Localization not working for "Today" and "Tomorrow" 

### ISSUE THREAD

**Issue by hildwin** [eouia/MMM-CalendarExt2#62]
If I change the language to "de-DE" there is still in the daily-view "Today", "Tomorrow" and the English date format in the headline. Only the third day is shown as "Freitag". 
What am I doing wrong?

```
{
			module: 'MMM-CalendarExt2',
			locale: "de-DE",
			config: {
			  calendars : [
				{
				  url: "webcal://192.168.178.231/familie.ics",
				},
			  ],
			  views: [
				{
					timeFormat:"HH.mm",
					dateFormat:"D. MMM",
					locale: "de-DE",
					mode: "daily",
				},
			  ],
			  scenes: [
				{
				  name: "DEFAULT",
				},
			  ],
			},
		},
```
![Anmerkung 2020-03-11 211514](https://user-images.githubusercontent.com/5394190/76459963-73350c00-63dd-11ea-95f9-cd1d322026e9.png)

**Comment by eouia** [comment]
Change your `slotTitleFormat` of `daily` view as your locale.  That is defined like this by default.
```js
slotTitleFormat: {
          sameDay: '[Today]',
          nextDay: '[Tomorrow]',
          nextWeek: 'dddd',
          lastDay: '[Yesterday]',
          lastWeek: '[Last] ddd',
          sameElse: 'ddd, M/D'
},
```
Ref, 
https://github.com/eouia/MMM-CalendarExt2/wiki/Localization Here I explained about event time format, but `slotTitleFormat` is the same.

**Comment by hildwin** [comment]
And I have to configure `slotSubTitleFormat`, too. Now I get it ... ;)
