### ISSUE TITLE
sceneClassName of undefined

### ISSUE THREAD

**Issue by acimail01** [eouia/MMM-CalendarExt2#67]
I wonder what could trigger this error?
CALEXT2_Scene.js:24 Uncaught TypeError: Cannot set property 'sceneClassName' of undefined
    at viewNames.forEach (CALEXT2_Scene.js:24)
    at Array.forEach (<anonymous>)
    at Scene.draw (CALEXT2_Scene.js:20)
    at setTimeout (MMM-CalendarExt2.js:336)

**Comment by eouia** [comment]
It means you have not proper view config. You probably have something wrong in `views:{}`

**Comment by acimail01** [comment]
Thank you very much for your hint! Used a view in the scene that was not defined.
