### ISSUE TITLE
There seems to be a limit to the number of events that can load

### ISSUE THREAD

**Issue by neoneddy** [eouia/MMM-CalendarExt2#7]
Below is the relevant part of my config file and validation that ICS files are being parsed.

What I've noticed is as I add more and more ICS files I'll start losing events being displayed into the future.  I've tried adjusting the maxItems to force more.  If I limit this to just my family calendar it seems to work, but as I add more it starts limiting how many concurrent events will show.

![image](https://user-images.githubusercontent.com/819083/52895818-243e8800-3185-11e9-89e0-040390d98477.png)

![image](https://user-images.githubusercontent.com/819083/52895775-9498d980-3184-11e9-86be-2999dc0d8a96.png)

`  module: 'MMM-CalendarExt2',
  config: {
	  rotateInterval:0,
	  firstDrawingDelay:5000,

    calendars : [
       {
	      name: "Family Calendar",
        url: "http://p24-calendars.icloud.com/published/2/AAAAAAAAAAAAAAAAAAAAAAnxvk6dWCSmUW3kKq4ORupmc5N8-oKpSk0yAZZHtGlwqLUC6DesVs_yY12kYaUyo7PlVn52ooOue8qqr2Tm43Q",
        afterDays: 60,
      }, 
     /*  {
	       name: "IHL Hockey",
	       className: "hockey",
        url: "https://www.benchapp.com/team/ical/169814-33617.ics",
      }, */
       {
	       name: "Wild Hockey",
	       className: "hockey",
        url: "http://www.mnwildadultleague.org/DesktopModules/SiPlay/SiteManagement/API/SiteInfo/GetTeamIcal?teamId=1225244",
      },
       {
	       name: "AHA Hockey",
	       className: "hockey",
        url: "http://p24-calendars.icloud.com/published/2/AAAAAAAAAAAAAAAAAAAAAFbutCjdXySRCw5Is28AXJAOkvwdjZpKUNDPxLThA4YE-VmN8rM7Ux576y9UJZJTbtjhJvdQycddRjuOhmQHUuA",
      },
    ],
    views: [
      {
		  name: "VIEW1",
		  mode: "month",
		  showWeeks: 0,
		  position: "bottom_bar",
		  title: "Family Schedule",
		  slotMaxHeight: "75px",
		  dateFormat: "M/D",
		  timeFormat:"h:mm A",
		  maxItems:100,
		  calendars: ["Family Calendar","Wild Hockey", "AHA Hockey"],
      },
    ],
    scenes: [
      {
        name: "MAIN",
        views:["VIEW1"]
      },
    ],
  },
`

**Comment by eouia** [comment]
There are two points to limit events being handled for performance.
-  `maxItems` of calendar configuration. It is limited to 100 by default. You can adjust the values in configuration. It is affected to calendar itself.
https://github.com/eouia/MMM-CalendarExt2/wiki/2b.-Configuration:Calendar#default-values-of-calendar

- `maxItems` of view configuration. It is also limited to 100 by default. You can also adjust. It is affected to view itself.
https://github.com/eouia/MMM-CalendarExt2/wiki/2c.-Configuration:View#common

You can also control the range of the valid events with these values.
```
beforeDays: 60, // Default
afterDays: 365, // Default
```
It means the event which has the date from 2 month ago to 1 year later will be vaild to handle.
https://github.com/eouia/MMM-CalendarExt2/wiki/2b.-Configuration:Calendar#default-values-of-calendar

**Comment by eouia** [comment]
And for concurrent events; adjust `maxIterations` of calendar config. But It needs much memory and CPU power, so use it carefully.

**Comment by eouia** [comment]
Anyway, I think your issue could be solved by, set bigger `maxItems` of **view** configuration. Your `maxItems` of `VIEW1` has limitation of 100, so some of events are missed. Set the value to 200 or 300 as your desire.
And, you can give a priority to event to be displayed and selected by your sorting algorithm. 
See the filetering and sorting section.
https://github.com/eouia/MMM-CalendarExt2/wiki/Filtering-and-Sorting

**Comment by neoneddy** [comment]
Ok thanks, that works!
