### ISSUE TITLE
New option for Month, Week Views

### ISSUE THREAD

**Issue by Al7ech** [eouia/MMM-CalendarExt2#72]
Hi, I'm having a great fun with your widget.

It's nothing special, but I thought that it would be great if I could turn on and off the `weeksmark`. If you are interested in this idea, I can send you a short pr.

Thanks.

**Comment by eouia** [comment]
You can hide it by CSS. add this into your `css/custom.css`

```css
.CX2 .weeksmark {
  display:none;
}
```
