### ISSUE TITLE
Issue with Previous / Next scene and typo mistake in calendarext2.js

### ISSUE THREAD

**Issue by bolish** [eouia/MMM-CalendarExt2#9]
Hi @eouia 

I'm facing an issue with the next / previous notification.
Indeed, Scene are not changing... it always stays fixed on the first scene (which is the default one for me).

Analysis help ':

- when autorotation ON : the scene rotation is working fine
- when autorotation off, despite several trials with notification, nothing works ':
       - `http://192.168.1.XX:8080/remote?action=NOTIFICATION&notification=CALEXT2_SCENE_NEXT&payload=null` is not working
      - sending from MMM-GroveGestures with `				"DOWN": {
						        notificationExec: {
						          notification: "CALEXT2_SCENE_PREVIOUS",
      						              payload: null,
							}
	      						},` also not working
    
Strange, isn't it?

By the way, I've noticed a mistake into calendarext2.js at line 12 ':

`      "CALEXT2_SECENE_NEXT": {
        exec: "sceneNext",
        payload: null,`

**Comment by eouia** [comment]
You are right. I had a mistake of confusing `nextScene` and `sceneNext`. I've fixed. `git pull` again and test it.

**Comment by bolish** [comment]
hahahaha,
the issue you solved is not the issue I was raising...But it indeed helped me to solve my problem. Well done.

You nevertheless still have to correct one typo in Line 12 for the notification name into the brackets 👍 
"CALEXT2_SECENE_NEXT" => "CALEXT2_SCENE_NEXT"
(sorry I don't know how to send you the corrected version).

Works fine now on my side.

Bye!

**Comment by eouia** [comment]
I’ve corrected it. Thanks again.
